version: 2

stack_defaults:
    befor_init:
        - ls -la

stacks:
    onboard1:
        project_root: "chaws"
        terraform_version: "1.5.6"
    compute-storage:
        project_root: "compute-storage"
        terraform_version: "1.5.7"
    database:
        project_root: "other"
        terraform_version: "1.5.7"